import { Permission } from './permissions';

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  ADMIN: [
    Permission.VIEW_STATUS_REPORTS,
    Permission.VIEW_DASHBOARDS,
    Permission.UPLOAD_DOCUMENTS,
    Permission.UPLOAD_STATE_LEVEL_DOCUMENTS,
    Permission.REVIEW_ULB_SUBMISSIONS,
    Permission.MESSAGE_USERS,
    Permission.APPROVE_ULB_SUBMISSIONS,
    Permission.PREPARE_GRANT_LETTERS,
    Permission.RECOMMEND_EXEMPTIONS,
    Permission.FINAL_SUBMIT_TO_STATE_DMA,
    Permission.FINAL_SUBMIT_TO_MOHUA,
    Permission.MANAGE_USERS,
    Permission.VIEW_MANAGED_USERS,
    Permission.CREATE_MANAGED_USER,
    Permission.UPDATE_MANAGED_USER,
    Permission.DELETE_MANAGED_USER,
  ],
  ULB: [
    Permission.VIEW_STATUS_REPORTS,
    Permission.UPLOAD_DOCUMENTS,
    Permission.MESSAGE_USERS,
    Permission.DELETE_DOCUMENTS,
    Permission.FINAL_SUBMIT_TO_STATE_DMA,
    Permission.MANAGE_USERS,
    Permission.VIEW_MANAGED_USERS,
    Permission.CREATE_MANAGED_USER,
    Permission.UPDATE_MANAGED_USER,
    Permission.DELETE_MANAGED_USER,
  ],
  'ULB-EDITOR': [
    Permission.VIEW_STATUS_REPORTS,
    Permission.UPLOAD_DOCUMENTS,
    Permission.DELETE_DOCUMENTS,
    Permission.MESSAGE_USERS,
  ],
  'ULB-VIEWER': [Permission.VIEW_STATUS_REPORTS],
  STATE: [
    Permission.VIEW_STATUS_REPORTS,
    Permission.VIEW_DASHBOARDS,
    Permission.UPLOAD_STATE_LEVEL_DOCUMENTS,
    Permission.REVIEW_ULB_SUBMISSIONS,
    Permission.MESSAGE_USERS,
    Permission.APPROVE_ULB_SUBMISSIONS,
    Permission.PREPARE_GRANT_LETTERS,
    Permission.RECOMMEND_EXEMPTIONS,
    Permission.FINAL_SUBMIT_TO_MOHUA,
    Permission.MANAGE_USERS,
    Permission.VIEW_MANAGED_USERS,
    Permission.CREATE_MANAGED_USER,
    Permission.UPDATE_MANAGED_USER,
    Permission.DELETE_MANAGED_USER,
  ],
  'STATE-EDITOR': [
    Permission.VIEW_STATUS_REPORTS,
    Permission.VIEW_DASHBOARDS,
    Permission.UPLOAD_STATE_LEVEL_DOCUMENTS,
    Permission.REVIEW_ULB_SUBMISSIONS,
    Permission.MESSAGE_USERS,
  ],
  'STATE-VIEWER': [Permission.VIEW_STATUS_REPORTS, Permission.VIEW_DASHBOARDS],
  // Legacy roles mapped to equivalent permission sets
  // XVIFC: [
  //   Permission.VIEW_STATUS_REPORTS,
  //   Permission.UPLOAD_DOCUMENTS,
  //   Permission.MESSAGE_USERS,
  //   Permission.FINAL_SUBMIT_TO_STATE_DMA,
  //   Permission.MANAGE_USERS,
  //   Permission.VIEW_MANAGED_USERS,
  //   Permission.CREATE_MANAGED_USER,
  //   Permission.UPDATE_MANAGED_USER,
  //   Permission.DELETE_MANAGED_USER,
  // ],
  // XVIFC_STATE: [
  //   Permission.VIEW_STATUS_REPORTS,
  //   Permission.VIEW_DASHBOARDS,
  //   Permission.UPLOAD_STATE_LEVEL_DOCUMENTS,
  //   Permission.REVIEW_ULB_SUBMISSIONS,
  //   Permission.MESSAGE_USERS,
  //   Permission.APPROVE_ULB_SUBMISSIONS,
  //   Permission.PREPARE_GRANT_LETTERS,
  //   Permission.RECOMMEND_EXEMPTIONS,
  //   Permission.FINAL_SUBMIT_TO_MOHUA,
  //   Permission.MANAGE_USERS,
  //   Permission.VIEW_MANAGED_USERS,
  //   Permission.CREATE_MANAGED_USER,
  //   Permission.UPDATE_MANAGED_USER,
  //   Permission.DELETE_MANAGED_USER,
  // ],
};
