export enum Permission {
  // Common read
  VIEW_STATUS_REPORTS = 'VIEW_STATUS_REPORTS',
  VIEW_DASHBOARDS = 'VIEW_DASHBOARDS',

  // STATE actions
  UPLOAD_STATE_LEVEL_DOCUMENTS = 'UPLOAD_STATE_LEVEL_DOCUMENTS',
  REVIEW_ULB_SUBMISSIONS = 'REVIEW_ULB_SUBMISSIONS',
  MESSAGE_USERS = 'MESSAGE_USERS',
  APPROVE_ULB_SUBMISSIONS = 'APPROVE_ULB_SUBMISSIONS',
  PREPARE_GRANT_LETTERS = 'PREPARE_GRANT_LETTERS',
  RECOMMEND_EXEMPTIONS = 'RECOMMEND_EXEMPTIONS',
  FINAL_SUBMIT_TO_MOHUA = 'FINAL_SUBMIT_TO_MOHUA',

  // State form actions
  VIEW_STATE_FORMS = 'VIEW_STATE_FORMS',
  EDIT_STATE_FORMS = 'EDIT_STATE_FORMS',
  FINAL_SUBMIT_STATE_FORMS = 'FINAL_SUBMIT_STATE_FORMS',

  // MoHUA actions
  REVIEW_STATE_SUBMISSIONS = 'REVIEW_STATE_SUBMISSIONS',
  SEND_REMINDERS_TO_STATES = 'SEND_REMINDERS_TO_STATES',
  REQUEST_INFO_FROM_STATES = 'REQUEST_INFO_FROM_STATES',
  APPROVE_STATE_SUBMISSIONS = 'APPROVE_STATE_SUBMISSIONS',
  ISSUE_OFFICE_MEMORANDUM = 'ISSUE_OFFICE_MEMORANDUM',
  FINAL_SUBMIT_TO_DOE = 'FINAL_SUBMIT_TO_DOE',

  // User management
  MANAGE_USERS = 'MANAGE_USERS',
  VIEW_MANAGED_USERS = 'VIEW_MANAGED_USERS',
  CREATE_MANAGED_USER = 'CREATE_MANAGED_USER',
  UPDATE_MANAGED_USER = 'UPDATE_MANAGED_USER',
  DELETE_MANAGED_USER = 'DELETE_MANAGED_USER',
}

export type Scope = 'ULB' | 'STATE' | 'MOHUA' | 'ADMIN';

export type AccessLevel = 'ADMIN' | 'EDITOR' | 'VIEWER';
