export const responseJson = {
  columns: [
    {
      label: 'S.No',
      key: 'sNo',
      sortable: false,
      class: 'th-common-cls',
      width: '3',
      sort: 0,
    },
    {
      label: '4mn+',
      key: 'id-1',
      sort: 1,
      link: 'nameLink',
      sortable: true,
      class: 'th-common-cls',
      width: '8',
    },
    {
      label: '1Mn to 4mn',
      key: 'id-2',
      sortable: false,
      class: 'th-common-cls',
      width: '6',
      sort: 0,
    },
    {
      label: '100K-1M',
      key: 'id-3',
      sortable: false,
      class: 'th-common-cls',
      width: '6',
      sort: 0,
    },
    {
      label: '100K-1M',
      key: 'id-4',
      sortable: true,
      class: 'th-common-cls',
      width: '7',
      sort: 0,
    },
  ],
  name: '',
  data: [
    {
      _id: '5dcf9d7216a06aed41c748dd',
      sNo: 1,
      'id-1': 'Amdavad Municipal Corporation',
      'id-2': 'Pune Municipal Corporation',
      'id-3': 'New Delhi Municipal Council',
      'id-4': 'Karjat Town Panchayat',
      nameLink: '/cfr/participated-ulbs/5dcf9d7216a06aed41c748dd',
    },
    {
      _id: '5dcf9d7216a06aed41c748e2',
      sNo: 2,
      'id-1': 'Surat Municipal Corporation',
      'id-2': 'Pimpari Chinchwad Municipal Corporation',
      'id-3': 'Adityapur Municipal Corporation',
      'id-4': 'Kannur Corporation',
      nameLink: '/cfr/participated-ulbs/5dcf9d7216a06aed41c748e2',
    },
    {
      _id: '5dcf9d7516a06aed41c748fa',
      sNo: 3,
      'id-1': 'Greater Hyderabad Municipal Corporation',
      'id-2': 'Navi Mumbai Municipal Corporation',
      'id-3': 'Panvel Municipal Corporation',
      'id-4': 'Peerzadiguda Municipal Corporation',
      nameLink: '/cfr/participated-ulbs/5dcf9d7516a06aed41c748fa',
    },
    {
      _id: '5fa25a6e0fb1d349c0fdfbc7',
      sNo: 4,
      'id-1': 'Greater Chennai Corporation',
      'id-2': 'Vadodara Municipal Corporation',
      'id-3': 'Vidisha Municipality',
      'id-4': 'Kadur Municipality',
      nameLink: '/cfr/participated-ulbs/5fa25a6e0fb1d349c0fdfbc7',
    },
    {
      _id: '5dcf9d7516a06aed41c748fb',
      sNo: 5,
      'id-1': null,
      'id-2': 'Vasai Virar City Municipal Corporation',
      'id-3': 'Shimoga City Municipal Council',
      'id-4': 'Ahmedabad Cantt',
      nameLink: '/cfr/participated-ulbs/5dcf9d7516a06aed41c748fb',
    },
    {
      _id: '5dcf9d7316a06aed41c748e7',
      sNo: 6,
      // "id-1": "Telangana",
      'id-2': 'Thane Municipal Corporation',
      'id-3': 'Shahjahanpur Municipal Corporation',
      'id-4': 'Boduppal Municipal Corporation',
      nameLink: '/cfr/participated-ulbs/5dcf9d7316a06aed41c748e7',
    },
    {
      _id: '5dcf9d7416a06aed41c748f0',
      sNo: 7,
      // "id-1": "Telangana",
      'id-2': 'Chhattisgarh',
      'id-3': 'Chhattisgarh',
      'id-4': 'Chhattisgarh',
      nameLink: '/cfr/participated-ulbs/5dcf9d7416a06aed41c748f0',
    },
    {
      _id: '5efd6a2fb5cd039b5c0cfed2',
      sNo: 8,
      // "id-1": "Telangana",
      'id-2': 'Chhattisgarh',
      'id-3': 'Chhattisgarh',
      'id-4': 'Chhattisgarh',
      nameLink: '/cfr/participated-ulbs/5efd6a2fb5cd039b5c0cfed2',
    },
    {
      _id: '5efd6a2fb5cd039b5c0cfed2',
      sNo: 9,
      // "id-1": "Telangana",
      'id-2': 'Chhattisgarh',
      'id-3': 'Chhattisgarh',
      'id-4': 'Chhattisgarh',
      nameLink: '/cfr/participated-ulbs/5efd6a2fb5cd039b5c0cfed2',
    },
    {
      _id: '5efd6a2fb5cd039b5c0cfed2',
      sNo: 10,
      // "id-1": "Telangana",
      'id-2': 'Chhattisgarh',
      'id-3': 'Chhattisgarh',
      'id-4': 'Chhattisgarh',
      nameLink: '/cfr/participated-ulbs/5efd6a2fb5cd039b5c0cfed2',
    },
  ],
  lastRow: ['', '', 'Total', '$sum', '$sum', '$sum', '$sum', '$sum'],
  total: 36,
};
