import { BorrowingsData, BorrowingsKeys } from '../../../../core/models/interfaces';

export const TABLE_STRUCTURE: BorrowingsData[] = [
  {
    table: '0',
    label: 'Details Of Instrument',
    key: 'typeOfInstruments',
    header: 'Type Of Instruments',
  },
  { table: '0', label: 'Details Of Instrument', key: 'term', header: 'Term' },
  { table: '0', label: 'Details Of Instrument', key: 'couponRate', header: 'Coupon Rate' },
  {
    table: '0',
    label: 'Details Of Instrument',
    key: 'interestPayment',
    header: 'Interest Payment',
  },
  { table: '0', label: 'Details Of Instrument', key: 'taxTreatment', header: 'Tax Treatment' },
  { table: '0', label: 'Details Of Instrument', key: 'repayment', header: 'Repayment' },
  { table: '1', label: 'Details Of Issue', key: 'dateOfIssue', header: 'Date Of Issue' },
  { table: '1', label: 'Details Of Issue', key: 'maturityDate', header: 'Maturity Date' },
  { table: '1', label: 'Details Of Issue', key: 'platform', header: 'Platform' },
  { table: '1', label: 'Details Of Issue', key: 'type', header: 'Type' },
  { table: '1', label: 'Details Of Issue', key: 'issueSize', header: 'Issue Size' },
  { table: '1', label: 'Details Of Issue', key: 'bidsReceived', header: 'Bids Received' },
  { table: '1', label: 'Details Of Issue', key: 'amountAccepted', header: 'Amount Accepted' },
  { table: '1', label: 'Details Of Issue', key: 'greenShoeOption', header: 'Green Shoe Option' },
  {
    table: '1',
    label: 'Details Of Issue',
    key: 'greenShowOptionAmount',
    header: 'Green Show Option Amount',
  },
  {
    table: '1',
    label: 'Details Of Issue',
    key: 'guaranteedByStateGovernment',
    header: 'Guaranteed By State Government',
  },
  {
    table: '1',
    label: 'Details Of Issue',
    key: 'guaranteeMechanism',
    header: 'Guarantee Mechanism',
  },
  { table: '2', label: 'Rating', key: 'CRISIL', header: 'CRISIL' },
  { table: '2', label: 'Rating', key: 'CARE', header: 'CARE' },
  { table: '2', label: 'Rating', key: 'ICRA', header: 'ICRA' },
  { table: '2', label: 'Rating', key: 'Brickwork', header: 'Brickwork' },
  { table: '2', label: 'Rating', key: 'Auicte  SMERA', header: 'Aucite / SMERA' },
  {
    table: '2',
    label: 'Rating',
    key: 'India Ratings & Research',
    header: 'India Ratings & Research',
  },
  { table: '2', label: 'Rating', key: 'Other Rating Agencies', header: 'Other Rating Agencies' },
  // { table: '2', label: 'Rating', key: 'Links to reports', header: 'Links To Reports' },
  { table: '3', label: 'Objective Of Issue', key: 'objectOfIssue', header: 'Object Of Issue' },
  { table: '4', label: 'Subscriber', key: 'whoCanInvest', header: 'Who Can Invest' },
  {
    table: '4',
    label: 'Subscriber',
    key: 'detailsOfSubscribers',
    header: 'Details Of Subscribers',
  },
  { table: '5', label: 'Advisors', key: 'transactionAdvisors', header: 'Transaction Advisors' },
  { table: '5', label: 'Advisors', key: 'trusteeForTheBond', header: 'Trustee For The Bond' },
  { table: '5', label: 'Advisors', key: 'registrarOfTheIssue', header: 'Registrar Of The Issue' },
  { table: '5', label: 'Advisors', key: 'auditorOfIssue', header: 'Auditor Of Issue' },
  { table: '5', label: 'Advisors', key: 'legalCounsel', header: 'Legal Counsel' },
  { table: '5', label: 'Advisors', key: 'escrowBanker', header: 'Escrow Banker<' },
  { table: '5', label: 'Advisors', key: 'arranger', header: 'Arranger' },
  {
    table: '6',
    label: 'Documents Available',
    key: 'draftInformationMemorandum',
    header: 'Draft Information Memorandum',
  },
  {
    table: '6',
    label: 'Documents Available',
    key: 'noticesFromPlatforms',
    header: 'Notices From Platforms',
  },
  { table: '6', label: 'Documents Available', key: 'others', header: 'Others' },
];

// export const DATA: BorrowingsKeys[] = [
//   {
//     ulbId: '5eb5844f76a3b61f40ba069a',
//     yearOfBondIssued: '2018',
//     typeOfInstruments:
//       'Unsecured Listed Taxable Non-Convertible Redeemable Bonds in the nature of Debentures Series- I',
//     term: '10 years',
//     couponRate: '8.90%',
//     interestPayment: 'Half Yearly',
//     taxTreatment: 'Taxable',
//     repayment: 'Bullet repayment at the end of bond term',
//     dateOfIssue: '22-02-2018',
//     maturityDate: '16-Feb-28',
//     platform: 'BSE Bond platform',
//     type: 'Private Placement',
//     issueSize: 'INR 200 crores',
//     issueSizeAmount: '200',
//     bidsReceived: 'INR 455 crores',
//     amountAccepted: 'INR 200 crores',
//     greenShoeOption: 'Not available',
//     greenShowOptionAmount: 'Not available',
//     guaranteedByStateGovernment: 'No',
//     guaranteeMechanism:
//       'Structured payment mechanism, where property tax and fee chargers are deposited in a separate no-lien escrow account',
//     CRISIL: 'Not applicable',
//     CARE: 'AA / Stable',
//     ICRA: 'Not applicable',
//     Brickwork: 'Not applicable',
//     'Auicte / SMERA': 'Not applicable',
//     'India Ratings & Research': 'AA / Stable',
//     'Other Rating Agencies': '',
//     'Links to reports':
//       'IRR -https://www.indiaratings.co.in/PressRelease?pressReleaseID=30548&title=India-Ratings-Assigns-Greater-Hyderabad-Municipal-Corporation%E2%80%99s-Proposed-NCDs-%E2%80%98Provisional-IND-AA%E2%80%99%2FStable\r\nCARE -\r\nhttp://www.careratings.com/upload/CompanyFiles/PR/Greater%20Hyderabad%20Municipal%20Corporation-01-31-2018.pdf',
//     objectOfIssue:
//       'Various development activities and other works under strategic road development programme including skyways, conflict free corridors etc',
//     whoCanInvest: 'Private Placement - Insurance, pension funds, primary dealers, banks etc',
//     detailsOfSubscribers: 'Not available',
//     transactionAdvisors: 'SPA Capital Advisors',
//     trusteeForTheBond: 'Not available',
//     registrarOfTheIssue: 'Not available',
//     auditorOfIssue: 'Not available',
//     legalCounsel: 'Not available',
//     escrowBanker: 'Not available',
//     arranger: 'SBI Capital Market',
//     draftInformationMemorandum: 'Not available',
//     noticesFromPlatforms:
//       'https://www.bseindia.com/markets/MarketInfo/DispNoticesNCirculars.aspx?Noticeid=%7BCB94CDB2-F97E-4430-950C-1CA3435E9995%7D&noticeno=20180221-26&dt=02/21/2018&icount=26&totcount=32&flag=0',
//     others: '',
//     modifiedAt: '2020-01-31T13:17:23.050Z',
//     createdAt: '2020-01-31T13:17:23.050Z',
//     // isActive: true,
//     _id: '5e342a737f468e1ef24bdc49',
//     ulb: 'Greater Hyderabad Municipal Corporation',
//     // __v: 0,
//     state: '5dcf9d7516a06aed41c748fb',
//   },
//   {
//     ulbId: null,
//     yearOfBondIssued: '2012',
//     typeOfInstruments: '2nd Instrument',
//     term: '5 years',
//     couponRate: '9.0%',
//     interestPayment: 'yearly',
//     taxTreatment: '',
//     repayment: '',
//     dateOfIssue: '2012',
//     maturityDate: '',
//     platform: '',
//     type: '',
//     issueSize: 'INR 51 Crore',
//     issueSizeAmount: '51',
//     bidsReceived: '',
//     amountAccepted: '',
//     greenShoeOption: '',
//     greenShowOptionAmount: '',
//     guaranteedByStateGovernment: '',
//     guaranteeMechanism: '',
//     CRISIL: '',
//     CARE: '',
//     ICRA: '',
//     Brickwork: '',
//     'Auicte / SMERA': '',
//     'India Ratings & Research': '',
//     'Other Rating Agencies': '',
//     'Links to reports': '',
//     objectOfIssue: '',
//     whoCanInvest: '',
//     detailsOfSubscribers: '',
//     transactionAdvisors: '',
//     trusteeForTheBond: '',
//     registrarOfTheIssue: '',
//     auditorOfIssue: '',
//     legalCounsel: '',
//     escrowBanker: '',
//     arranger: '',
//     draftInformationMemorandum: '',
//     noticesFromPlatforms: '',
//     others: 'http://www.janaagraha.org/files/City-Systems-Brief-Municipal-Bonds.pdf',
//     modifiedAt: '2020-01-31T13:17:23.050Z',
//     createdAt: '2020-01-31T13:17:23.050Z',
//     // isActive: true,
//     _id: '5e342a737f468e1ef24bdc51',
//     ulb: 'Tamil Nadu State Government',
//     // __v: 0,
//     state: '5dcf9d7516a06aed41c748fa',
//   },
//   {
//     ulbId: null,
//     yearOfBondIssued: '2010',
//     typeOfInstruments: '3rd Instrument',
//     term: '',
//     couponRate: '7%',
//     interestPayment: 'quaterly',
//     taxTreatment: '',
//     repayment: '',
//     dateOfIssue: '2010',
//     maturityDate: '',
//     platform: '',
//     type: '',
//     issueSize: 'INR 300 Crore',
//     issueSizeAmount: '300',
//     bidsReceived: '',
//     amountAccepted: '',
//     greenShoeOption: '',
//     greenShowOptionAmount: '',
//     guaranteedByStateGovernment: '',
//     guaranteeMechanism: '',
//     CRISIL: '',
//     CARE: '',
//     ICRA: '',
//     Brickwork: '',
//     'Auicte / SMERA': '',
//     'India Ratings & Research': '',
//     'Other Rating Agencies': '',
//     'Links to reports': '',
//     objectOfIssue: "Lending to ULB's through Directorate of Municipal Administration",
//     whoCanInvest: '',
//     detailsOfSubscribers: '',
//     transactionAdvisors: '',
//     trusteeForTheBond: '',
//     registrarOfTheIssue: '',
//     auditorOfIssue: '',
//     legalCounsel: '',
//     escrowBanker: '',
//     arranger: '',
//     draftInformationMemorandum: '',
//     noticesFromPlatforms: '',
//     others: 'http://www.janaagraha.org/files/City-Systems-Brief-Municipal-Bonds.pdf',
//     modifiedAt: '2020-01-31T13:17:23.050Z',
//     createdAt: '2020-01-31T13:17:23.050Z',
//     // isActive: true,
//     _id: '5e342a737f468e1ef24bdc54',
//     ulb: 'Karnataka Water and Sanitation Pooled Fund',
//     // __v: 0,
//     state: '5dcf9d7316a06aed41c748ec',
//   },
//   {
//     ulbId: null,
//     yearOfBondIssued: '2004',
//     typeOfInstruments: '4th Instrument',
//     term: '7 years',
//     couponRate: '5.20%',
//     interestPayment: 'half-yearly',
//     taxTreatment: 'Non- Taxable',
//     repayment: '',
//     dateOfIssue: '2004',
//     maturityDate: '',
//     platform: '',
//     type: '',
//     issueSize: 'INR 42 Crore',
//     issueSizeAmount: '42',
//     bidsReceived: '',
//     amountAccepted: '',
//     greenShoeOption: '',
//     greenShowOptionAmount: '',
//     guaranteedByStateGovernment: '',
//     guaranteeMechanism: '',
//     CRISIL: '',
//     CARE: '',
//     ICRA: 'AA',
//     Brickwork: '',
//     'Auicte / SMERA': '',
//     'India Ratings & Research': '',
//     'Other Rating Agencies': '',
//     'Links to reports': '',
//     objectOfIssue: 'Water supply',
//     whoCanInvest: '',
//     detailsOfSubscribers: '',
//     transactionAdvisors: '',
//     trusteeForTheBond: '',
//     registrarOfTheIssue: '',
//     auditorOfIssue: '',
//     legalCounsel: '',
//     escrowBanker: '',
//     arranger: '',
//     draftInformationMemorandum: '',
//     noticesFromPlatforms: '',
//     others:
//       'https://www.brookings.edu/wp-content/uploads/2016/08/metro_20160818_indiasmartcitiesreport.pdf',
//     modifiedAt: '2020-01-31T13:17:23.050Z',
//     createdAt: '2020-01-31T13:17:23.050Z',
//     // isActive: true,
//     _id: '5e342a737f468e1ef24bdc5b',
//     ulb: 'Chennai Metropolitan Water Supply and Sewerage Board',
//     // __v: 0,
//     state: '5dcf9d7516a06aed41c748fa',
//   },
//   {
//     ulbId: '5dd24729437ba31f7eb42ed2',
//     yearOfBondIssued: '2004',
//     typeOfInstruments: '5th Instrument',
//     term: '9 years',
//     couponRate: '7.75%',
//     interestPayment: '',
//     taxTreatment: 'Taxable',
//     repayment: '',
//     dateOfIssue: '2004',
//     maturityDate: '',
//     platform: '',
//     type: 'Private',
//     issueSize: 'INR 20 Crore',
//     issueSizeAmount: '20',
//     bidsReceived: '',
//     amountAccepted: '',
//     greenShoeOption: '',
//     greenShowOptionAmount: '',
//     guaranteedByStateGovernment: 'No',
//     guaranteeMechanism: 'Escrow Bank Account had cash inflow from property tax',
//     CRISIL: '',
//     CARE: '',
//     ICRA: '',
//     Brickwork: '',
//     'Auicte / SMERA': '',
//     'India Ratings & Research': '',
//     'Other Rating Agencies': 'AA-',
//     'Links to reports': '',
//     objectOfIssue: 'Water Supply Project',
//     whoCanInvest: '',
//     detailsOfSubscribers: '',
//     transactionAdvisors: '',
//     trusteeForTheBond: '',
//     registrarOfTheIssue: '',
//     auditorOfIssue: '',
//     legalCounsel: '',
//     escrowBanker: '',
//     arranger: '',
//     draftInformationMemorandum: '',
//     noticesFromPlatforms: '',
//     others:
//       'http://southasia.berkeley.edu/sites/default/files/shared/events/21st_Century_Indian_City/Vaidya-MARKET-BASED_FINANCING_URBAN_INFRASTRUCTURE_INDIA.DOC',
//     modifiedAt: '2020-01-31T13:17:23.050Z',
//     createdAt: '2020-01-31T13:17:23.050Z',
//     // isActive: true,
//     _id: '5e342a737f468e1ef24bdc5d',
//     ulb: 'Vishakapatnam Municipal Corporation',
//     // __v: 0,
//     state: '5dcf9d7216a06aed41c748dd',
//   },
//   {
//     ulbId: '5dd24729437ba31f7eb42ed2',
//     yearOfBondIssued: '2004',
//     typeOfInstruments: '6th Instrument',
//     term: '0 years',
//     couponRate: '',
//     interestPayment: 'freely',
//     taxTreatment: '',
//     repayment: '',
//     dateOfIssue: '2004',
//     maturityDate: '',
//     platform: '',
//     type: '',
//     issueSize: 'INR 50 Crore',
//     issueSizeAmount: '50',
//     bidsReceived: '',
//     amountAccepted: '',
//     greenShoeOption: '',
//     greenShowOptionAmount: '',
//     guaranteedByStateGovernment: '',
//     guaranteeMechanism: '',
//     CRISIL: '',
//     CARE: '',
//     ICRA: '',
//     Brickwork: '',
//     'Auicte / SMERA': '',
//     'India Ratings & Research': '',
//     'Other Rating Agencies': '',
//     'Links to reports': '',
//     objectOfIssue: 'Water Supply Project',
//     whoCanInvest: '',
//     detailsOfSubscribers: '',
//     transactionAdvisors: '',
//     trusteeForTheBond: '',
//     registrarOfTheIssue: '',
//     auditorOfIssue: '',
//     legalCounsel: '',
//     escrowBanker: '',
//     arranger: '',
//     draftInformationMemorandum: '',
//     noticesFromPlatforms: '',
//     others: 'http://www.janaagraha.org/files/City-Systems-Brief-Municipal-Bonds.pdf',
//     modifiedAt: '2020-01-31T13:17:23.050Z',
//     createdAt: '2020-01-31T13:17:23.050Z',
//     // isActive: true,
//     _id: '5e342a737f468e1ef24bdc5e',
//     ulb: 'Vishakapatnam Municipal Corporation',
//     // __v: 0,
//     state: '5dcf9d7216a06aed41c748dd',
//   },
// ];
