// Generated by https://quicktype.io

export interface IULBWithPopulationResponse {
  message: string;
  success: boolean;
  data: ULBWithMapData[];
}

export interface ULBWithMapData {
  auditStatus: "audited" | "unaudited" | "auditNA";
  population: number;
  area: number;
  location: Location;
  _id: string;
  state: State;
  code: string;
  name: string;
}

export interface Location {
  lat: string;
  lng: string;
}

export enum State {
  The5Dcf9D7216A06Aed41C748DD = "5dcf9d7216a06aed41c748dd",
  The5Dcf9D7216A06Aed41C748Df = "5dcf9d7216a06aed41c748df",
  The5Dcf9D7216A06Aed41C748E2 = "5dcf9d7216a06aed41c748e2",
  The5Dcf9D7316A06Aed41C748E7 = "5dcf9d7316a06aed41c748e7",
  The5Dcf9D7316A06Aed41C748E8 = "5dcf9d7316a06aed41c748e8",
  The5Dcf9D7316A06Aed41C748Eb = "5dcf9d7316a06aed41c748eb",
  The5Dcf9D7316A06Aed41C748Ec = "5dcf9d7316a06aed41c748ec",
  The5Dcf9D7316A06Aed41C748Ed = "5dcf9d7316a06aed41c748ed",
  The5Dcf9D7416A06Aed41C748Ef = "5dcf9d7416a06aed41c748ef",
  The5Dcf9D7416A06Aed41C748F0 = "5dcf9d7416a06aed41c748f0",
  The5Dcf9D7416A06Aed41C748F3 = "5dcf9d7416a06aed41c748f3",
  The5Dcf9D7416A06Aed41C748F5 = "5dcf9d7416a06aed41c748f5",
  The5Dcf9D7516A06Aed41C748F7 = "5dcf9d7516a06aed41c748f7",
  The5Dcf9D7516A06Aed41C748F8 = "5dcf9d7516a06aed41c748f8",
  The5Dcf9D7516A06Aed41C748Fa = "5dcf9d7516a06aed41c748fa",
  The5Dcf9D7516A06Aed41C748Fb = "5dcf9d7516a06aed41c748fb",
  The5Dcf9D7516A06Aed41C748Fc = "5dcf9d7516a06aed41c748fc",
  The5Dcf9D7516A06Aed41C748Fd = "5dcf9d7516a06aed41c748fd",
  The5Dcf9D7516A06Aed41C748Fe = "5dcf9d7516a06aed41c748fe",
  The5Dcf9D7616A06Aed41C748Ff = "5dcf9d7616a06aed41c748ff"
}
