// import { financialData } from "./xviFinanceDataJson";
import { financialData } from './xviFinanceDataJsonApi';
import { slb } from './xviFcSlb';

const basicTab = {
  _id: '666764fa1d285021388bedba',
  key: 'demographicData',
  icon: '',
  formType: 'form2',
  label: 'Demographic Data',
  id: 's1',
  displayPriority: 1,
  __v: 0,
  data: [
    {
      key: 'nameOfUlb',
      readonly: true,
      class: '',
      label: 'Name of ULB',
      position: '1',
      quesPos: 1,
      required: true,
      info: '',
      placeHolder: '',
      formFieldType: 'text',
      canShow: true,
      validations: [
        {
          name: 'required',
          validator: 'required',
          message: 'Please fill in this required field.',
        },
      ],
      year: [],
      status: 'Na',
      value: 'Dhanbad Municipal Corporation',
      isDraft: true,
    },
    {
      key: 'nameOfState',
      readonly: true,
      class: '',
      label: 'Name of State/Union Territory ',
      position: '2',
      quesPos: 2,
      required: true,
      info: '',
      placeHolder: '',
      formFieldType: 'text',
      canShow: true,
      validations: [
        {
          name: 'required',
          validator: 'required',
          message: 'Please fill in this required field.',
        },
      ],
      year: [],
      status: 'Na',
      value: 'Jharkhand',
      isDraft: true,
    },
    {
      key: 'pop2011',
      readonly: false,
      class: '',
      label: 'Population as per Census 2011',
      position: '3',
      quesPos: 3,
      required: true,
      info: '',
      placeHolder: '',
      formFieldType: 'number',
      canShow: true,
      validations: [
        {
          name: 'required',
          validator: 'required',
          message: 'Please fill in this required field.',
        },
        {
          name: 'min',
          validator: 0,
          message: 'Please enter a number between 0 and 100000000.',
        },
        {
          name: 'max',
          validator: 100000000,
          message: 'Please enter a number between 0 and 100000000.',
        },
        {
          name: 'decimal',
          validator: 0,
          message: 'Please enter a whole number for this field.',
        },
        [],
      ],
      year: [],
      warning: [
        {
          value: 0,
          condition: 'eq',
          message: 'Are you sure you want to continue with 0',
        },
      ],
      sumOf: [],
      max: 100000000,
      min: 0,
      decimal: 0,
      status: 'Na',
      value: '78324',
      isDraft: true,
    },
    {
      key: 'popApril2024',
      readonly: false,
      class: '',
      label: 'Population as per 01 April 2024',
      position: '4',
      quesPos: 4,
      required: true,
      info: '',
      placeHolder: '',
      formFieldType: 'number',
      canShow: true,
      validations: [
        {
          name: 'required',
          validator: 'required',
          message: 'Please fill in this required field.',
        },
        {
          name: 'min',
          validator: 0,
          message: 'Please enter a number between 0 and 100000000.',
        },
        {
          name: 'max',
          validator: 100000000,
          message: 'Please enter a number between 0 and 100000000.',
        },
        {
          name: 'decimal',
          validator: 0,
          message: 'Please enter a whole number for this field.',
        },
        [],
      ],
      year: [],
      warning: [
        {
          value: 0,
          condition: 'eq',
          message: 'Are you sure you want to continue with 0',
        },
      ],
      sumOf: [],
      max: 100000000,
      min: 0,
      decimal: 0,
      status: 'Na',
      value: '25',
      isDraft: true,
    },
    {
      key: 'areaOfUlb',
      readonly: false,
      class: '',
      label: 'Area of the ULB (in Sq. Km.)',
      position: '5',
      quesPos: 5,
      required: true,
      info: '',
      placeHolder: '',
      formFieldType: 'number',
      canShow: true,
      validations: [
        {
          name: 'required',
          validator: 'required',
          message: 'Please fill in this required field.',
        },
        {
          name: 'min',
          validator: 0.1,
          message: 'Please enter a number between 0.1 and 1000.',
        },
        {
          name: 'max',
          validator: 1000,
          message: 'Please enter a number between 0.1 and 1000.',
        },
        {
          name: 'decimal',
          validator: 2,
          message: 'Please enter number with at most 2 places.',
        },
        [],
      ],
      year: [],
      warning: [
        {
          value: 0,
          condition: 'eq',
          message: 'Are you sure you want to continue with 0',
        },
      ],
      sumOf: [],
      max: 1000,
      min: 0.1,
      decimal: 2,
      status: 'Na',
      value: '124.3',
      isDraft: true,
    },
    {
      key: 'yearOfElection',
      readonly: false,
      class: '',
      label: "Which is the latest year when ULB's election was held?",
      position: '6',
      quesPos: 6,
      required: true,
      info: '',
      placeHolder: '',
      formFieldType: 'dropdown',
      canShow: true,
      validations: [
        {
          name: 'required',
          validator: 'required',
          message: 'Please fill in this required field.',
        },
      ],
      year: [],
      options: [
        '2024-25',
        '2023-24',
        '2022-23',
        '2021-22',
        '2020-21',
        '2019-20',
        '2018-19',
        '2017-18',
        '2016-17',
        '2015-16',
        'Before 2015-16',
      ],
      reason: '',
      status: 'Na',
      value: '2022-23',
      isDraft: true,
    },
    {
      key: 'isElected',
      readonly: false,
      class: '',
      label: 'Is the elected body in place as on 01 April 2024?',
      position: '7',
      quesPos: 7,
      required: true,
      info: '',
      placeHolder: '',
      formFieldType: 'radio',
      canShow: true,
      validations: [
        {
          name: 'required',
          validator: 'required',
          message: 'Please fill in this required field.',
        },
      ],
      year: [],
      options: ['Yes', 'No'],
      reason: '',
      status: 'Na',
      value: 'Yes',
      isDraft: true,
    },
    {
      key: 'yearOfConstitution',
      readonly: false,
      class: '',
      label: 'In which year was the ULB constituted?',
      position: '8',
      quesPos: 8,
      required: true,
      info: '',
      placeHolder: '',
      formFieldType: 'dropdown',
      canShow: true,
      validations: [
        {
          name: 'required',
          validator: 'required',
          message: 'Please fill in this required field.',
        },
      ],
      year: [],
      options: [
        '2022-23',
        '2021-22',
        '2020-21',
        '2019-20',
        '2018-19',
        '2017-18',
        '2016-17',
        'In 2015-16',
        'Before 2015-16',
      ],
      reason: '',
      status: 'Na',
      value: 'Before 2015-16',
      isDraft: true,
    },
    {
      key: 'yearOfSlb',
      readonly: false,
      class: '',
      label: 'From which year is Service Level Benchmark data available?',
      position: '9',
      quesPos: 9,
      required: true,
      info: '',
      placeHolder: '',
      formFieldType: 'dropdown',
      canShow: true,
      validations: [
        {
          name: 'required',
          validator: 'required',
          message: 'Please fill in this required field.',
        },
      ],
      year: [],
      options: [
        '2022-23',
        '2021-22',
        '2020-21',
        '2019-20',
        '2018-19',
        '2017-18',
        '2016-17',
        '2015-16',
      ],
      reason: '',
      status: 'Na',
      value: '2017-18',
      isDraft: true,
    },
  ],
};
const uploadDoc = {
  _id: '665df95e73de1812233ecc01',
  key: 'uploadDoc',
  icon: '',
  text: '',
  formType: 'form1',
  label: 'View/ Upload Document',
  id: 's3',
  displayPriority: 3,
  __v: 0,
  data: [
    {
      key: 'auditedAnnualFySt',
      label: 'Copy of Audited Annual Financial Statements preferably in English',
      postion: '',
      required: true,
      info: '',
      placeHolder: '',
      formFieldType: 'file',
      canShow: true,
      max: 5,
      min: 0,
      bottomText: 'Maximum of 5MB',
      instruction: [
        {
          instruction:
            "Annual Financial Statement should include: Income and Expenditure Statement, Balance Sheet, Schedules to IES and BS, Auditor's Report and if available Receipts & Payments Statement.",
        },
        {
          instruction:
            ' All documents pertaining to a specific financial year should be combined into a single PDF before uploading & should not exceed 20 MB.',
        },
        {
          instruction:
            'Please use the following format for naming the documents to be uploaded: nameofthedocument_FY_ULB Name. || Example: Annual accounts_15-16_Jaipur municipal corporation',
        },
      ],
      year: [
        {
          warning: [],
          label: 'FY 2022-23',
          key: 'fy2022-23_auditedAnnualFySt',
          postion: 1,
          type: 'auditedAnnualFySt',
          formFieldType: 'file',
          value: '',
          isPdfAvailable: true,
          file: {
            name: 'testName2022-23',
            url: 'https://www.test.com/2022-23.pdf',
          },
          fileAlreadyOnCf: [
            {
              name: '',
              url: '',
              type: '',
              label: '',
            },
          ],
          fileRejectOptions: [
            'Balance Sheet',
            'Schedules To Balance Sheet',
            'Income And Expenditure',
            'Schedules To Income And Expenditure',
            'Cash Flow Statement',
            'Auditor Report',
          ],
          verifyStatus: 3, // 1-pending, 2- accept, 3- reject
          rejectOption: '',
          rejectReason: 'Test 321',
          allowedFileTypes: ['pdf'],
        },
        {
          warning: [],
          label: 'FY 2021-22',
          key: 'fy2021-22_auditedAnnualFySt',
          postion: 2,
          type: 'auditedAnnualFySt',
          formFieldType: 'file',
          value: '',
          isPdfAvailable: true,
          file: {
            name: '',
            url: '',
          },
          fileAlreadyOnCf: [
            {
              name: '',
              url: '',
              type: '',
              label: '',
            },
          ],
          fileRejectOptions: [
            'Balance Sheet',
            'Schedules To Balance Sheet',
            'Income And Expenditure',
            'Schedules To Income And Expenditure',
            'Cash Flow Statement',
            'Auditor Report',
          ],
          verifyStatus: 2,
        },
        {
          warning: [],
          label: 'FY 2020-21',
          key: 'fy2020-21_auditedAnnualFySt',
          postion: 3,
          type: 'auditedAnnualFySt',
          formFieldType: 'file',
          value: '',
          isPdfAvailable: false,
          file: {
            name: 'testName2020-21',
            url: 'https://www.test.com/2020-21.pdf',
          },
          fileAlreadyOnCf: [
            {
              name: '',
              url: '',
              type: '',
              label: '',
            },
          ],
          fileRejectOptions: [
            'Balance Sheet',
            'Schedules To Balance Sheet',
            'Income And Expenditure',
            'Schedules To Income And Expenditure',
            'Cash Flow Statement',
            'Auditor Report',
          ],
        },
        {
          warning: [],
          label: 'FY 2019-20',
          key: 'fy2019-20_auditedAnnualFySt',
          postion: 4,
          type: 'auditedAnnualFySt',
          formFieldType: 'file',
          value: '',
          isPdfAvailable: true,
          file: {
            name: 'testName2019-20',
            url: 'https://www.test.com/2019-20.pdf',
          },
          fileAlreadyOnCf: [
            {
              name: 'Balance Sheet 2019-20.pdf',
              url: '/objects/5f7b285f-8bc6-4bdf-a216-1f53605e9ab2.pdf',
              type: 'bal_sheet',
              label: 'Balance Sheet',
            },
            {
              name: 'Schedule 1-20 Balance sheet 2019-20.pdf',
              url: '/objects/16c32fbe-3576-4ea0-ab94-af37cfb05569.pdf',
              type: 'bal_sheet_schedules',
              label: 'Schedules To Balance Sheet',
            },
            {
              name: 'Income & Expenditure Statement 2019-20.pdf',
              url: '/objects/4f505458-5f1a-4475-900f-bcc65f224996.pdf',
              type: 'inc_exp',
              label: 'Income And Expenditure',
            },
            {
              name: 'Schedule 21-40 Income Exp. 2019-20.pdf',
              url: '/objects/2c580cae-5ca7-4c50-80f3-3debfe5175c1.pdf',
              type: 'inc_exp_schedules',
              label: 'Schedules To Income And Expenditure',
            },
            {
              name: 'BPT19.pdf',
              url: '/objects/c3d0135c-1f23-4880-ae60-6dce44c7e2ef.pdf',
              type: 'cash_flow',
              label: 'Cash Flow Statement',
            },
            {
              name: 'Audit Report  2019-20.pdf',
              url: '/objects/57ce419b-1db3-4102-9743-7bcbd0786563.pdf',
              type: 'auditor_report',
              label: 'Auditor Report',
            },
          ],
          fileRejectOptions: [
            'Balance Sheet',
            'Schedules To Balance Sheet',
            'Income And Expenditure',
            'Schedules To Income And Expenditure',
            'Cash Flow Statement',
            'Auditor Report',
          ],
        },
        {
          warning: [],
          label: 'FY 2018-19',
          key: 'fy2018-19_auditedAnnualFySt',
          postion: 5,
          type: 'auditedAnnualFySt',
          formFieldType: 'file',
          value: '',
          isPdfAvailable: false,
          file: {
            name: 'testName2018-19',
            url: 'https://www.test.com/2018-19.pdf',
          },
          fileAlreadyOnCf: [
            {
              name: '',
              url: '',
              type: '',
              label: '',
            },
          ],
          fileRejectOptions: [
            'Balance Sheet',
            'Schedules To Balance Sheet',
            'Income And Expenditure',
            'Schedules To Income And Expenditure',
            'Cash Flow Statement',
            'Auditor Report',
          ],
        },
        {
          warning: [],
          label: 'FY 2017-18',
          key: 'fy2017-18_auditedAnnualFySt',
          postion: 6,
          type: 'auditedAnnualFySt',
          formFieldType: 'file',
          value: '',
          isPdfAvailable: false,
          file: {
            name: 'testName2017-18',
            url: 'https://www.test.com/2017-18.pdf',
          },
          fileAlreadyOnCf: [
            {
              name: '',
              url: '',
              type: '',
              label: '',
            },
          ],
          fileRejectOptions: [
            'Balance Sheet',
            'Schedules To Balance Sheet',
            'Income And Expenditure',
            'Schedules To Income And Expenditure',
            'Cash Flow Statement',
            'Auditor Report',
          ],
        },
        {
          warning: [],
          label: 'FY 2016-17',
          key: 'fy2016-17_auditedAnnualFySt',
          postion: 7,
          type: 'auditedAnnualFySt',
          formFieldType: 'file',
          value: '',
          isPdfAvailable: false,
          file: {
            name: 'testName2016-17',
            url: 'https://www.test.com/2016-17.pdf',
          },
          fileAlreadyOnCf: [
            {
              name: '',
              url: '',
              type: '',
              label: '',
            },
          ],
          fileRejectOptions: [
            'Balance Sheet',
            'Schedules To Balance Sheet',
            'Income And Expenditure',
            'Schedules To Income And Expenditure',
            'Cash Flow Statement',
            'Auditor Report',
          ],
        },
        {
          warning: [],
          label: 'FY 2015-16',
          key: 'fy2015-16_auditedAnnualFySt',
          postion: 8,
          type: 'auditedAnnualFySt',
          formFieldType: 'file',
          value: '',
          isPdfAvailable: false,
          file: {
            name: 'testName2015-16',
            url: 'https://www.test.com/2015-16.pdf',
          },
          fileAlreadyOnCf: [
            {
              name: '',
              url: '',
              type: '',
              label: '',
            },
          ],
          fileRejectOptions: [
            'Balance Sheet',
            'Schedules To Balance Sheet',
            'Income And Expenditure',
            'Schedules To Income And Expenditure',
            'Cash Flow Statement',
            'Auditor Report',
          ],
        },
      ],
      status: 'Na',
      value: '',
      isDraft: true,
      readonly: false,
    },
  ],
};
const accountPractice = {
  _id: '666764fa1d285021388bedbd',
  key: 'accountPractice',
  icon: '',
  formType: 'form2',
  label: 'Accounting Practice',
  id: 's4',
  displayPriority: 4,
  __v: 0,
  data: [
    {
      key: 'staffing',
      section: 'accordion',
      formFieldType: 'questionnaire',
      label: 'II.Staffing - Finance & Accounts Department',
      data: [
        {
          key: 'totSanction',
          readonly: false,
          class: '',
          label: 'What is the total sanctioned posts for finance & accounts related positions?',
          position: '11',
          quesPos: 63,
          required: true,
          info: '',
          placeHolder: '',
          formFieldType: 'number',
          canShow: true,
          validations: [
            {
              name: 'required',
              validator: 'required',
              message: 'Please fill in this required field.',
            },
            {
              name: 'min',
              validator: 0,
              message: 'Please enter a number between 0 and 9999.',
            },
            {
              name: 'max',
              validator: 9999,
              message: 'Please enter a number between 0 and 9999.',
            },
            {
              name: 'decimal',
              validator: 0,
              message: 'Please enter a whole number for this field.',
            },
            [],
          ],
          year: [],
          warning: [
            {
              value: 0,
              condition: 'eq',
              message: 'Are you sure you want to continue with 0',
            },
          ],
          sumOf: [],
          max: 9999,
          min: 0,
          decimal: 0,
          status: 'Na',
          value: '',
          isDraft: true,
        },
        {
          key: 'totVacancy',
          readonly: false,
          class: '',
          label: 'What is the total vacancy across finance & accounts related positions?',
          position: '12',
          quesPos: 64,
          required: true,
          info: '',
          placeHolder: '',
          formFieldType: 'number',
          canShow: true,
          validations: [
            {
              name: 'required',
              validator: 'required',
              message: 'Please fill in this required field.',
            },
            {
              name: 'min',
              validator: 0,
              message: 'Please enter a number between 0 and 9999.',
            },
            {
              name: 'max',
              validator: 9999,
              message: 'Please enter a number between 0 and 9999.',
            },
            {
              name: 'decimal',
              validator: 0,
              message: 'Please enter a whole number for this field.',
            },
            {
              name: 'lt',
              validator: 0,
              field: 'totSanction',
              message:
                "'Total vacancy across finance & accounts related positions' cannot be greater than 'Total sanctioned posts for finance & accounts related positions '",
            },
          ],
          year: [],
          warning: [
            {
              value: 0,
              condition: 'eq',
              message: 'Are you sure you want to continue with 0',
            },
          ],
          sumOf: [],
          max: 9999,
          min: 0,
          decimal: 0,
          status: 'Na',
          value: '',
          isDraft: true,
        },
        {
          key: 'accPosition',
          readonly: false,
          class: '',
          label:
            'How many finance & accounts related positions currently are filled on contractual basis or outsourced?',
          position: '13',
          quesPos: 65,
          required: true,
          info: '',
          placeHolder: '',
          formFieldType: 'number',
          canShow: true,
          validations: [
            {
              name: 'required',
              validator: 'required',
              message: 'Please fill in this required field.',
            },
            {
              name: 'min',
              validator: 0,
              message: 'Please enter a number between 0 and 9999.',
            },
            {
              name: 'max',
              validator: 9999,
              message: 'Please enter a number between 0 and 9999.',
            },
            {
              name: 'decimal',
              validator: 0,
              message: 'Please enter a whole number for this field.',
            },
            [],
          ],
          year: [],
          warning: [
            {
              value: 0,
              condition: 'eq',
              message: 'Are you sure you want to continue with 0',
            },
          ],
          sumOf: [],
          max: 9999,
          min: 0,
          decimal: 0,
          status: 'Na',
          value: '',
          isDraft: true,
        },
      ],
    },
  ],
};

const reviewSubmit = {
  key: 'reviewSubmit',
  label: 'Review & Submit',
  displayPriority: 5,
};

export const tabsJson = {
  data: {
    tabs: [
      basicTab,
      // financialData,
      // uploadDoc,
      // accountPractice,
      slb,
      // reviewSubmit
    ],
  },
};
