// Generated by https://quicktype.io

export interface IULBTypeListResponse {
  timestamp: number;
  success: boolean;
  message: string;
  data: IULBType[];
}

export interface IULBType {
  modifiedAt: string;
  createdAt: string;
  isActive: boolean;
  _id: string;
  name: string;
  __v: number;
}
