// Generated by https://quicktype.io

export interface IULBProfileRequestResponse {
  timestamp: number;
  success: boolean;
  message: string;
  data: IULBProfileRequest[];
  total?: number;
}

export interface IULBProfileRequest {
  _id: string;
  ulbType: null | { name: string; _id: string };
  natureOfUlb: null;
  name: null | string;
  regionalName: null;
  code: null;
  state: null;
  wards: number | null;
  area: null;
  population: null;
  location: null;
  amrut: null;
  commissionerName?: null | string;
  commissionerEmail?: string;
  commissionerConatactNumber?: string;
  accountantName?: string;
  accountantEmail?: string;
  accountantConatactNumber?: string;
  status: string;
  history: any[];
  modifiedAt: string;
  createdAt: string;
  isActive: boolean;
  ulb: {
    _id: string;
    code: string;
    name: string;
    ulbType: {
      _id: string;
      name: string;
    };
  };
  actionTakenBy: string;
  __v: number;
}

export interface IFullULBProfileRequest extends IULBProfileRequest {
  old: IULBProfileRequest & {
    ulb: {
      wards: number | null;
      area: null;
      population: null;
    };
  };
}
