name: CI

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - feature/added-prettier-lint

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm run test --code-coverage --watch=false --browsers=ChromeHeadless

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.2.0
        with:
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
